"use client";

import type { InventoryItem } from "@/lib/types";
import { daysUntil, formatDate } from "@/lib/date";
interface Props { items: InventoryItem[]; onToggleConsumed: (id: string) => void; onRemove: (id: string) => void; }
type Tone = "expired" | "soon" | "ok";
function badge(item: InventoryItem): { text: string; tone: Tone } { const d = daysUntil(item.expiryDate); if (d < 0) return { text: `Expired ${Math.abs(d)}d ago`, tone: "expired" }; if (d === 0) return { text: "Today", tone: "soon" }; if (d === 1) return { text: "Tomorrow", tone: "soon" }; if (d <= 2) return { text: `${d} days`, tone: "soon" }; return { text: `${d} days`, tone: "ok" }; }
const toneClass: Record<Tone, string> = { expired: "bg-[#fbe8e5] text-danger", soon: "bg-[#fff3cf] text-[#8b681e]", ok: "bg-accent-soft text-accent-strong" };
function quantity(item: InventoryItem) { return [item.amount, item.unit].filter(Boolean).join(" ").trim(); }
export function InventoryList({ items, onToggleConsumed, onRemove }: Props) { const sorted = [...items].sort((a, b) => { if (a.consumed !== b.consumed) return a.consumed ? 1 : -1; return a.expiryDate.localeCompare(b.expiryDate); }); if (sorted.length === 0) return <div className="card-surface flex flex-col items-center rounded-3xl border-dashed p-10 text-center"><div className="mb-4 grid size-12 place-items-center rounded-2xl bg-accent-soft text-xl text-accent">+</div><p className="font-bold">Your fridge is ready for its first item.</p><p className="mt-1 text-sm text-muted">Add something above and we&apos;ll keep an eye on freshness.</p></div>; return <ul className="flex flex-col gap-2">{sorted.map((item, index) => { const b = badge(item); const qty = quantity(item); return <li key={item.id} className={`row-hover card-surface flex items-center gap-3 rounded-2xl px-4 py-3 animate-rise delay-${Math.min(index + 1, 3)} ${item.consumed ? "opacity-45" : ""}`}><button type="button" onClick={() => onToggleConsumed(item.id)} title={item.consumed ? "Mark as not used" : "Mark as used"} aria-label={item.consumed ? `Mark ${item.name} as not used` : `Mark ${item.name} as used`} className={`grid size-7 shrink-0 place-items-center rounded-full border-2 text-xs font-bold transition-all ${item.consumed ? "border-accent bg-accent text-white" : "border-line text-transparent hover:border-accent"}`}>✓</button><div className="min-w-0 flex-1"><div className={`truncate text-sm font-bold ${item.consumed ? "line-through" : ""}`}>{item.name}</div><div className="truncate text-xs text-muted">{[item.category, qty].filter(Boolean).join(" · ")}</div></div><span className="hidden shrink-0 text-xs text-muted md:block">{formatDate(item.expiryDate)}</span><span className={`shrink-0 rounded-full px-2.5 py-1 text-[11px] font-bold ${toneClass[b.tone]}`}>{b.text}</span><button type="button" onClick={() => onRemove(item.id)} title={`Remove ${item.name}`} aria-label={`Remove ${item.name}`} className="grid size-7 shrink-0 place-items-center rounded-lg text-muted transition hover:bg-[#fbe8e5] hover:text-danger">×</button></li>; })}</ul>; }
